### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by alexanderhalpern** [shawnmalik1/StatZone#3]

**Comment by Ryguy-1** [comment]
the issues section should be populated only with specific lines cited and examples of input along with expected output.

**Comment by alexanderhalpern** [comment]
> the issues section should be populated only with specific lines cited and examples of input along with expected output.

Ok fantastic point. I shall implement that methodology in my future posting of issues.

**Comment by Ryguy-1** [comment]
Great thanks sir. Chip Chip
